### PR TITLE
gap-packages Ownership Update

### PR DESCRIPTION
**Pull request by ZachNewbery**
This PR looks to change any instances relevant to my GitHub account to gap-packages. It is to be merged when ownership can be transferred to gap-packages. 

It is essentially a replica of the reverted PR #14, and is to be merged after submission of my dissertation in January.

### CODE REVIEW

**Comment by fingolfin** [comment]
If you'd like to transfer ownership to `gap-packages`, that can be done at any time, and is independent from depositing your package.

Just put in a transfer request and perhaps email me afterwards (or @olexandr-konovalov who can also admin the `gap-packages` org)

**Review by olexandr-konovalov — APPROVED** [review]
Thanks @ZachNewbery !

**Comment by ZachNewbery** [comment]
Would it be easiest to make a release integrating my later changes before migrating ownership to gap-packages? Or should it be done after? @olexandr-konovalov

**Comment by olexandr-konovalov** [comment]
@ZachNewbery first migrate, then make a release. You're already a member of https://github.com/orgs/gap-packages/people so I guess you can migrate it yourself - please ask if help needed!

**Pull request merged**
